### ISSUE TITLE
remove example/.gitignore

### ISSUE THREAD

**Issue by bendichter** [nwb-extensions/staged-extensions#5]
I think this is redundant with the root `.gitignore`

**Comment by rly** [comment]
The `example/.gitignore` will get copied over to the new repository. The root `.gitignore` is for this repo. Though, this repo shouldn't generate any files or do anything, so there isn't a need for a root `.gitignore`

**Comment by rly** [comment]
@oruebel is there a need for either .gitignore file? No outputs should be generated in this repo, and we curate all changes via PRs anyway. The generated repo only needs to include the `ndx-meta.yaml` and a `README.md` file.

**Comment by rly** [comment]
The inner .gitignore has been removed.

**Comment by oruebel** [comment]
> is there a need for either .gitignore file? No outputs should be generated in this repo, and we curate all changes via PRs anyway.

In general, the advantage of .gitignore is that it prevents files you don't want in the repo from being added in the first place, whereas review of PRs means fixing the problem after-the-fact. Providing users with a template for a .gitignore is I think a good idea, in part because users may not be familiar with it, however, that could just be part of the automation process when you setup the repo rather than being part of the example. However, I agree that it is more critical that we have a good .gitignore template in the template repo for creating extensions, rather than here, since that repo will have actual code.
